apiVersion: v1
kind: ConfigMap
metadata:
    name: helm-multi-env-config
    namespace: {{ .Values.namespace }}
data: 
{{ printf "environments/configmap.%s.yaml" .Values.namespace | .Files.Get | indent 2 }}