apiVersion: v1
kind: Secret
metadata:
    name: helm-multi-env-config
    namespace: {{ .Values.namespace }}
type: Opaque
data: 
{{ printf "environments/secrets.%s.yaml" .Values.namespace | .Files.Get | indent 2 }}